# Generated by Django 4.1.7 on 2023-03-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('evaluation', models.IntegerField(verbose_name='Оценки')),
                ('items', models.ManyToManyField(to='api.item', verbose_name='Предметы')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название класса')),
                ('year', models.IntegerField(verbose_name='Год обучения')),
                ('students', models.ManyToManyField(to='api.student', verbose_name='Ученики')),
            ],
        ),
    ]
