# Generated by Django 4.1.7 on 2023-03-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fio',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='student',
            name='evaluation',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
    ]
