# Generated by Django 4.1.7 on 2023-03-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_class_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='year',
        ),
    ]
